---
title: "Simulation study"
output: html_document
date: '2024-03-29'
---

```{r}
library(doParallel)
registerDoParallel(cores = detectCores())
library(tpc)
library(conflicted)
conflict_prefer("tpc", "tpc")
source("TGES_function.R")
source("Simulate_functions.R")
```

```{r}
#connectivity parameter (between 0 and 1) (in tier og across tier)
#incpar <- 0.8
incpar_vec <- c(0.1,0.9)

#accpar <- 0.2
accpar_vec <- c(0.1,0.9)

#Nodes in each tier
#tino <- c(2,5)
#tino_vec <- list(c(2,3),c(1,1,1,1,1))#,c(5,5),c(2,3,2,2,1)) #21 sek uden 10 nodes, 3.8 min med 10 nodes

#Number of nodes
numno_vec <- c(7,20)

#Number of tiers
numti_vec <- c(2,5)

#Order vector for tges
  # tior <- c()
  # for (k in 1:length(tino)){
  #   tior <- c(tior,rep(k,tino[k]))
  # }

#Upper and lower bound for coefficients
lB <- 0.1
uB <- 1

#Number of observations
#n <- 30
n_vec <- c(30,1000)

#Number of simulations
k <- 100
```





# Alternative way of simulating (Less dataframes)
```{r}
numdfperf <- length(n_vec)*length(incpar_vec)*length(accpar_vec)*length(numti_vec)*length(numno_vec)

ges_perfomance <- data.frame(adjprecision = rep(NA,numdfperf),
                           adjrecall = rep(NA,numdfperf),
                           intierdirprecision = rep(NA,numdfperf),
                           intierdirrecall = rep(NA,numdfperf),
                           Obs = rep(NA,numdfperf),
                           Inpar = rep(NA,numdfperf),
                           Acpar = rep(NA,numdfperf),
                           Numtiers = rep(NA,numdfperf),
                           Numnodes = rep(NA,numdfperf),
                           Comptime = rep(NA,numdfperf))
tges_perfomance <- data.frame(adjprecision = rep(NA,numdfperf),
                           adjrecall = rep(NA,numdfperf),
                           dirprecision = rep(NA,numdfperf),
                           dirrecall = rep(NA,numdfperf),
                           Obs = rep(NA,numdfperf),
                           Inpar = rep(NA,numdfperf),
                           Acpar = rep(NA,numdfperf),
                           Numtiers = rep(NA,numdfperf),
                           Numnodes = rep(NA,numdfperf),
                           Comptime = rep(NA,numdfperf))
sim_perfomance <- data.frame(adjprecision = rep(NA,numdfperf),
                           adjrecall = rep(NA,numdfperf),
                           dirprecision = rep(NA,numdfperf),
                           dirrecall = rep(NA,numdfperf),
                           intierdirprecision = rep(NA,numdfperf),
                           intierdirrecall = rep(NA,numdfperf),
                           Obs = rep(NA,numdfperf),
                           Inpar = rep(NA,numdfperf),
                           Acpar = rep(NA,numdfperf),
                           Numtiers = rep(NA,numdfperf),
                           Numnodes = rep(NA,numdfperf),
                           Comptime = rep(NA,numdfperf))
tpc_perfomance <- data.frame(adjprecision = rep(NA,numdfperf),
                           adjrecall = rep(NA,numdfperf),
                           dirprecision = rep(NA,numdfperf),
                           dirrecall = rep(NA,numdfperf),
                           Obs = rep(NA,numdfperf),
                           Inpar = rep(NA,numdfperf),
                           Acpar = rep(NA,numdfperf),
                           Numtiers = rep(NA,numdfperf),
                           Numnodes = rep(NA,numdfperf),
                           Comptime = rep(NA,numdfperf))


t_vs_ges_perfomance <- data.frame(adjprecision = rep(NA,numdfperf),
                           adjrecall = rep(NA,numdfperf),
                           intierdirprecision = rep(NA,numdfperf),
                           intierdirrecall = rep(NA,numdfperf),
                           Uap = rep(NA,numdfperf),
                           Lap = rep(NA,numdfperf),
                           Uar = rep(NA,numdfperf),
                           Lar = rep(NA,numdfperf),
                           Udp = rep(NA,numdfperf),
                           Ldp = rep(NA,numdfperf),
                           Udr = rep(NA,numdfperf),
                           Ldr = rep(NA,numdfperf),
                           Obs = rep(NA,numdfperf),
                           Inpar = rep(NA,numdfperf),
                           Acpar = rep(NA,numdfperf),
                           Numtiers = rep(NA,numdfperf),
                           Numnodes = rep(NA,numdfperf))
t_vs_sim_perfomance <- data.frame(adjprecision = rep(NA,numdfperf),
                           adjrecall = rep(NA,numdfperf),
                           dirprecision = rep(NA,numdfperf),
                           dirrecall = rep(NA,numdfperf),
                           Uap = rep(NA,numdfperf),
                           Lap = rep(NA,numdfperf),
                           Uar = rep(NA,numdfperf),
                           Lar = rep(NA,numdfperf),
                           Udp = rep(NA,numdfperf),
                           Ldp = rep(NA,numdfperf),
                           Udr = rep(NA,numdfperf),
                           Ldr = rep(NA,numdfperf),
                           Obs = rep(NA,numdfperf),
                           Inpar = rep(NA,numdfperf),
                           Acpar = rep(NA,numdfperf),
                           Numtiers = rep(NA,numdfperf),
                           Numnodes = rep(NA,numdfperf))
t_vs_tpc_perfomance <- data.frame(adjprecision = rep(NA,numdfperf),
                           adjrecall = rep(NA,numdfperf),
                           dirprecision = rep(NA,numdfperf),
                           dirrecall = rep(NA,numdfperf),
                           Uap = rep(NA,numdfperf),
                           Lap = rep(NA,numdfperf),
                           Uar = rep(NA,numdfperf),
                           Lar = rep(NA,numdfperf),
                           Udp = rep(NA,numdfperf),
                           Ldp = rep(NA,numdfperf),
                           Udr = rep(NA,numdfperf),
                           Ldr = rep(NA,numdfperf),
                           Obs = rep(NA,numdfperf),
                           Inpar = rep(NA,numdfperf),
                           Acpar = rep(NA,numdfperf),
                           Numtiers = rep(NA,numdfperf),
                           Numnodes = rep(NA,numdfperf))

```


```{r}

count <- 0
countdiv <- numdfperf
t <- 1
start_time <- Sys.time()

for (n in n_vec){
  for (incpar in incpar_vec){
    for (accpar in accpar_vec){
      for (num_no in numno_vec){
        for (num_ti in numti_vec){
          tior <- sort(c(sample(c(1:num_ti),(num_no-num_ti),replace = T),1:num_ti))
          tino <- c()
          for (o in 1:num_ti){
            tino <- c(tino,sum(tior == o))
          }  
          
          tgesdf <- data.frame(adjprecision = rep(NA,k), adjrecall = rep(NA,k),
                           dirprecision = rep(NA,k), dirrecall = rep(NA,k),
                           intierdirprecision = rep(NA,k), intierdirrecall = rep(NA,k))
          
          gesdf <- data.frame(adjprecision = rep(NA,k), adjrecall = rep(NA,k),
                           intierdirprecision = rep(NA,k), intierdirrecall = rep(NA,k))
          
          simpletgesdf <- data.frame(adjprecision = rep(NA,k), adjrecall = rep(NA,k),
                           dirprecision = rep(NA,k), dirrecall = rep(NA,k),
                           intierdirprecision = rep(NA,k), intierdirrecall = rep(NA,k))
          
          tpcdf <- data.frame(adjprecision = rep(NA,k), adjrecall = rep(NA,k),
                           dirprecision = rep(NA,k), dirrecall = rep(NA,k))
          
          tges_execution_time <- ges_execution_time <- sim_execution_time <- tpc_execution_time <- 0
          
          set.seed(t+100)
          
          iter_df <- foreach(i = 1:k,
                             .combine = 'rbind',
                             .packages = c("pcalg","graph","RBGL","tpc","causalDisco")
                             ) %dopar% {
            source("TGES_classes_only.R")
            iter_vec <- rep(NA,24)
            
            weightadjmat <- randtierDAG(incpar,accpar,tino, lB = lB, uB = uB)
            
            data <- rmvTDAG(n, weightadjmat)
            adjmat <- ceiling(weightadjmat/uB)
            adjmat <- dag2tmpdag(adjmatrix = adjmat,odr = tior)
            
            t_score <- new("GaussL0penIntScoreORDER", order = tior
                            , data = data 
                            ,  use.cpp = F)
            
            ges_score <- new("GaussL0penIntScoreORDER"
                            , data = data 
                            ,  use.cpp = F)
            
            
            #TGES
            tges_start_time <- Sys.time()
            tges_fit <- tges(t_score, order = tior)
            t_est_adjmat <- createAdjMatrixFromList(tges_fit$.in.edges)
            tges_end_time <- Sys.time()
            #tges_execution_time <- tges_execution_time + (tges_end_time - tges_start_time)
            iter_vec[21] <- (tges_end_time - tges_start_time)
            
            #GES
            ges_start_time <- Sys.time()
            ges_fit <- ges(ges_score)
            ges_est_adjmat <- createAdjMatrixFromList(ges_fit$essgraph$.in.edges)
            ges_end_time <- Sys.time()
            #ges_execution_time <- ges_execution_time + (ges_end_time - ges_start_time)
            iter_vec[22] <- (ges_end_time - ges_start_time)
            
            #Simple TGES
            sim_start_time <- Sys.time()
            simple_t_est_adjmat <- ges_to_simple_tges_adj(ges_fit, tior)
            sim_end_time <- Sys.time()
            #sim_execution_time <- sim_execution_time + (sim_end_time - sim_start_time)
            iter_vec[23] <- (sim_end_time - sim_start_time)
            
            #TPC
            tpc_start_time <- Sys.time()
            tpc_fit <- tpc::tpc(suffStat = list(C = cor(data), n = n),
                           indepTest = gaussCItest, alpha = 0.01, tiers = tior, p = num_no)
            tpc_est_adjmat <- as(tpc_fit, "matrix")
            tpc_end_time <- Sys.time()
            #tpc_execution_time <- tpc_execution_time + (tpc_end_time - tpc_start_time)
            iter_vec[24] <- (tpc_end_time - tpc_start_time)
            
            #Metrics
          
            adjconf <- confusion(t_est_adjmat,adjmat, type = "adj")
            dirconf <- confusion(t_est_adjmat,adjmat, type = "dir")
            intierdirconf <- intier_confusion(t_est_adjmat,adjmat, type = "dir", tior)
            #tgesdf$adjprecision[i] 
            iter_vec[1] <-  precision(adjconf)
            #tgesdf$adjrecall[i] 
            iter_vec[2] <-  recall(adjconf)
            #tgesdf$dirprecision[i] 
            iter_vec[3] <-  precision(dirconf)
            #tgesdf$dirrecall[i] 
            iter_vec[4] <-  recall(dirconf)
            #tgesdf$intierdirprecision[i] 
            iter_vec[5] <- precision(intierdirconf)
            #tgesdf$intierdirrecall[i] 
            iter_vec[6] <- recall(intierdirconf)
            
            adjconf <- confusion(ges_est_adjmat,adjmat, type = "adj")
            dirconf <- intier_confusion(ges_est_adjmat,adjmat, type = "dir",tior)
            #gesdf$adjprecision[i] 
            iter_vec[7] <-  precision(adjconf)
            #gesdf$adjrecall[i]
            iter_vec[8] <-  recall(adjconf)
            #gesdf$intierdirprecision[i]
            iter_vec[9] <-  precision(dirconf)
            #gesdf$intierdirrecall[i]
            iter_vec[10] <-  recall(dirconf)
            
            adjconf <- confusion(simple_t_est_adjmat,adjmat, type = "adj")
            dirconf <- confusion(simple_t_est_adjmat,adjmat, type = "dir")
            intierdirconf <- intier_confusion(simple_t_est_adjmat,adjmat, type = "dir", tior)
            #simpletgesdf$adjprecision[i]
            iter_vec[11] <-  precision(adjconf)
            #simpletgesdf$adjrecall[i]
            iter_vec[12] <-  recall(adjconf)
            #simpletgesdf$dirprecision[i]
            iter_vec[13] <-  precision(dirconf)
            #simpletgesdf$dirrecall[i]
            iter_vec[14] <-  recall(dirconf)
            #simpletgesdf$intierdirprecision[i]
            iter_vec[15] <- precision(intierdirconf)
            #simpletgesdf$intierdirrecall[i]
            iter_vec[16] <- recall(intierdirconf)
            
            
            adjconf <- confusion(tpc_est_adjmat,adjmat, type = "adj")
            dirconf <- confusion(tpc_est_adjmat,adjmat, type = "dir")
            #tpcdf$adjprecision[i]
            iter_vec[17] <-  precision(adjconf)
            #tpcdf$adjrecall[i]
            iter_vec[18] <-  recall(adjconf)
            #tpcdf$dirprecision[i]
            iter_vec[19] <-  precision(dirconf)
            #tpcdf$dirrecall[i]
            iter_vec[20] <-  recall(dirconf)
            return(iter_vec)
            
          }
          #print percantage of simulation done
          count = count + 1 
          print(round(100*count/countdiv))
          #Input vector from foreach into df's
            tgesdf$adjprecision <- iter_df[,1] 
            tgesdf$adjrecall <- iter_df[,2]
            tgesdf$dirprecision <- iter_df[,3]
            tgesdf$dirrecall <- iter_df[,4]
            tgesdf$intierdirprecision <- iter_df[,5]
            tgesdf$intierdirrecall <- iter_df[,6]
            gesdf$adjprecision <- iter_df[,7]
            gesdf$adjrecall <- iter_df[,8] 
            gesdf$intierdirprecision <- iter_df[,9]
            gesdf$intierdirrecall <- iter_df[,10]
            simpletgesdf$adjprecision<- iter_df[,11]
            simpletgesdf$adjrecall <- iter_df[,12]
            simpletgesdf$dirprecision <- iter_df[,13]
            simpletgesdf$dirrecall <- iter_df[,14]
            simpletgesdf$intierdirprecision <- iter_df[,15]
            simpletgesdf$intierdirrecall <- iter_df[,16]
            tpcdf$adjprecision <- iter_df[,17]
            tpcdf$adjrecall <- iter_df[,18]
            tpcdf$dirprecision <- iter_df[,19]
            tpcdf$dirrecall <- iter_df[,20]
            tges_execution_time <- sum(iter_df[,21])
            ges_execution_time <- sum(iter_df[,22])
            sim_execution_time <- sum(iter_df[,23])
            tpc_execution_time <- sum(iter_df[,24]) 
          
          #Input parameters
           tpc_perfomance$Obs[t] <- sim_perfomance$Obs[t] <- tges_perfomance$Obs[t] <- ges_perfomance$Obs[t] <- t_vs_ges_perfomance$Obs[t] <- t_vs_sim_perfomance$Obs[t] <- t_vs_tpc_perfomance$Obs[t] <- n
           tpc_perfomance$Inpar[t] <- sim_perfomance$Inpar[t] <- tges_perfomance$Inpar[t] <- ges_perfomance$Inpar[t] <- t_vs_ges_perfomance$Inpar[t] <- t_vs_sim_perfomance$Inpar[t] <-  t_vs_tpc_perfomance$Inpar[t] <- incpar
           tpc_perfomance$Acpar[t] <- sim_perfomance$Acpar[t] <- tges_perfomance$Acpar[t] <- ges_perfomance$Acpar[t] <- t_vs_ges_perfomance$Acpar[t] <- t_vs_sim_perfomance$Acpar[t] <-  t_vs_tpc_perfomance$Acpar[t] <- accpar
           tpc_perfomance$Numtiers[t] <- sim_perfomance$Numtiers[t] <- tges_perfomance$Numtiers[t] <- ges_perfomance$Numtiers[t] <- t_vs_ges_perfomance$Numtiers[t] <- t_vs_sim_perfomance$Numtiers[t] <-  t_vs_tpc_perfomance$Numtiers[t] <- num_ti
           tpc_perfomance$Numnodes[t] <- sim_perfomance$Numnodes[t] <- tges_perfomance$Numnodes[t] <- ges_perfomance$Numnodes[t] <- t_vs_ges_perfomance$Numnodes[t] <- t_vs_sim_perfomance$Numnodes[t] <-  t_vs_tpc_perfomance$Numnodes[t] <- num_no
          
          #Input perfomance metrics
           #AP mean
           tges_perfomance$adjprecision[t] <- mean(tgesdf$adjprecision)
           ges_perfomance$adjprecision[t] <- mean(gesdf$adjprecision)
           sim_perfomance$adjprecision[t] <- mean(simpletgesdf$adjprecision)
           tpc_perfomance$adjprecision[t] <- mean(tpcdf$adjprecision)
           t_vs_ges_perfomance$adjprecision[t] <- mean(tgesdf$adjprecision-gesdf$adjprecision)
           t_vs_sim_perfomance$adjprecision[t] <- mean(tgesdf$adjprecision-simpletgesdf$adjprecision)
           t_vs_tpc_perfomance$adjprecision[t] <- mean(tgesdf$adjprecision-tpcdf$adjprecision)
           #AP quantiles
           t_vs_ges_perfomance$Uap[t] <- quantile(tgesdf$adjprecision-gesdf$adjprecision,p = 0.975)
           t_vs_ges_perfomance$Lap[t] <- quantile(tgesdf$adjprecision-gesdf$adjprecision,p = 0.025)
           t_vs_sim_perfomance$Uap[t] <- quantile(tgesdf$adjprecision-simpletgesdf$adjprecision,p = 0.975)
           t_vs_sim_perfomance$Lap[t] <- quantile(tgesdf$adjprecision-simpletgesdf$adjprecision,p = 0.025)
           t_vs_tpc_perfomance$Uap[t] <- quantile(tgesdf$adjprecision-tpcdf$adjprecision,p = 0.975)
           t_vs_tpc_perfomance$Lap[t] <- quantile(tgesdf$adjprecision-tpcdf$adjprecision,p = 0.025)
           #AR mean
           tges_perfomance$adjrecall[t] <- mean(tgesdf$adjrecall)
           ges_perfomance$adjrecall[t] <- mean(gesdf$adjrecall)
           sim_perfomance$adjrecall[t] <- mean(simpletgesdf$adjrecall)
           tpc_perfomance$adjrecall[t] <- mean(tpcdf$adjrecall)
           t_vs_ges_perfomance$adjrecall[t] <- mean(tgesdf$adjrecall-gesdf$adjrecall)
           t_vs_sim_perfomance$adjrecall[t] <- mean(tgesdf$adjrecall-simpletgesdf$adjrecall)
           t_vs_tpc_perfomance$adjrecall[t] <- mean(tgesdf$adjrecall-tpcdf$adjrecall)
           #AR quantiles
           t_vs_ges_perfomance$Uar[t] <- quantile(tgesdf$adjrecall-gesdf$adjrecall,p = 0.975)
           t_vs_ges_perfomance$Lar[t] <- quantile(tgesdf$adjrecall-gesdf$adjrecall,p = 0.025)
           t_vs_sim_perfomance$Uar[t] <- quantile(tgesdf$adjrecall-simpletgesdf$adjrecall,p = 0.975)
           t_vs_sim_perfomance$Lar[t] <- quantile(tgesdf$adjrecall-simpletgesdf$adjrecall,p = 0.025)
           t_vs_tpc_perfomance$Uar[t] <- quantile(tgesdf$adjrecall-tpcdf$adjrecall,p = 0.975)
           t_vs_tpc_perfomance$Lar[t] <- quantile(tgesdf$adjrecall-tpcdf$adjrecall,p = 0.025)
           #DP mean
           tges_perfomance$dirprecision[t] <- mean(tgesdf$dirprecision)
           ges_perfomance$intierdirprecision[t] <- mean(gesdf$intierdirprecision,na.rm = T)
           sim_perfomance$dirprecision[t] <- mean(simpletgesdf$dirprecision)
           sim_perfomance$intierdirprecision[t] <- mean(simpletgesdf$intierdirprecision)
           tpc_perfomance$dirprecision[t] <- mean(tpcdf$dirprecision)
           t_vs_ges_perfomance$intierdirprecision[t] <- mean(tgesdf$intierdirprecision-gesdf$intierdirprecision, na.rm = T)
           t_vs_sim_perfomance$dirprecision[t] <- mean(tgesdf$dirprecision-simpletgesdf$dirprecision)
           t_vs_tpc_perfomance$dirprecision[t] <- mean(tgesdf$dirprecision-tpcdf$dirprecision)
           #DP quantiles
           t_vs_ges_perfomance$Udp[t] <- quantile(tgesdf$intierdirprecision-gesdf$intierdirprecision,p = 0.975, na.rm = T)
           t_vs_ges_perfomance$Ldp[t] <- quantile(tgesdf$intierdirprecision-gesdf$intierdirprecision,p = 0.025, na.rm = T)
           t_vs_sim_perfomance$Udp[t] <- quantile(tgesdf$dirprecision-simpletgesdf$dirprecision,p = 0.975)
           t_vs_sim_perfomance$Ldp[t] <- quantile(tgesdf$dirprecision-simpletgesdf$dirprecision,p = 0.025)
           t_vs_tpc_perfomance$Udp[t] <- quantile(tgesdf$dirprecision-tpcdf$dirprecision,p = 0.975)
           t_vs_tpc_perfomance$Ldp[t] <- quantile(tgesdf$dirprecision-tpcdf$dirprecision,p = 0.025)
           #DR mean
           tges_perfomance$dirrecall[t] <- mean(tgesdf$dirrecall)
           ges_perfomance$intierdirrecall[t] <- mean(gesdf$intierdirrecall,na.rm = T)
           sim_perfomance$dirrecall[t] <- mean(simpletgesdf$dirrecall)
           sim_perfomance$intierdirrecall[t] <- mean(simpletgesdf$intierdirrecall)
           tpc_perfomance$dirrecall[t] <- mean(tpcdf$dirrecall)
           t_vs_ges_perfomance$intierdirrecall[t] <- mean(tgesdf$intierdirrecall-gesdf$intierdirrecall, na.rm = T)
           t_vs_sim_perfomance$dirrecall[t] <- mean(tgesdf$dirrecall-simpletgesdf$dirrecall)
           t_vs_tpc_perfomance$dirrecall[t] <- mean(tgesdf$dirrecall-tpcdf$dirrecall)
           #DR quantiles
           t_vs_ges_perfomance$Udr[t] <- quantile(tgesdf$intierdirrecall-gesdf$intierdirrecall,p = 0.975, na.rm = T)
           t_vs_ges_perfomance$Ldr[t] <- quantile(tgesdf$intierdirrecall-gesdf$intierdirrecall,p = 0.025, na.rm = T)
           t_vs_sim_perfomance$Udr[t] <- quantile(tgesdf$dirrecall-simpletgesdf$dirrecall,p = 0.975)
           t_vs_sim_perfomance$Ldr[t] <- quantile(tgesdf$dirrecall-simpletgesdf$dirrecall,p = 0.025)
           t_vs_tpc_perfomance$Udr[t] <- quantile(tgesdf$dirrecall-tpcdf$dirrecall,p = 0.975)
           t_vs_tpc_perfomance$Ldr[t] <- quantile(tgesdf$dirrecall-tpcdf$dirrecall,p = 0.025)
           
           
           #Computation time
           tges_perfomance$Comptime[t] <- tges_execution_time
           ges_perfomance$Comptime[t] <- ges_execution_time
           sim_perfomance$Comptime[t] <- sim_execution_time
           tpc_perfomance$Comptime[t] <- tpc_execution_time
          t = t + 1
        }
      }
      
    }
    
  }
  
  
  
}
end_time <- Sys.time()
execution_time <- end_time - start_time
print(execution_time)
#save.image("k100df20NewConf.Rdata")
```


# Make tables
```{r}
load("k100df20NewConf.Rdata")
library(xtable)
```


```{r}
table <- data.frame(matrix(NA, nrow = 8, ncol = 4*4))
cnames <- c()
par3 <- 1
method_vec <- c("tges","sim","tpc") #choose relevant methods
metric <- "dirrecall" #Choose relevant metric
for (method in method_vec){
for (par1 in numno_vec){
  for (par2 in numti_vec){
    table[,par3] <- eval(parse(text = paste(method,"_perfomance$",metric,
                                            "[",method,"_perfomance$Numnodes == ",par1," & ",method,"_perfomance$Numtiers == ",par2,
                                            " & ",method,"_perfomance$Inpar != 0.6"," & ",method,"_perfomance$Acpar != 0.6","]",sep = "")))
    cnames <- c(cnames,paste(method,par1,par2,sep = "_"))
    par3 = par3 +1 
  }
}
  }
colnames(table) <- cnames
#make latex table
xtable(table)
```

